//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKRUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInfo
    {
        public int LogID { get; set; }
        public Nullable<int> EPC { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> InTIME { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<System.TimeSpan> UsageTime { get; set; }
        public Nullable<double> PaySum { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> PileID { get; set; }
        public Nullable<int> UserFrequence { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<double> PriceRate { get; set; }
        public Nullable<int> BuildingID { get; set; }
    }
}
