//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKRUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logrfid
    {
        public string EPC_ID { get; set; }
        public Nullable<long> count { get; set; }
        public Nullable<int> wire { get; set; }
        public int ReadID { get; set; }
    }
}
