//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKRUSER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PileInfo
    {
        public int DistrictID { get; set; }
        public int PileID { get; set; }
        public Nullable<int> OccupiedType { get; set; }
        public Nullable<int> ChargingType { get; set; }
        public Nullable<int> DamagedType { get; set; }
        public Nullable<int> UsageTimes { get; set; }
        public Nullable<int> BuildingID { get; set; }
    }
}
