//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKRUSER.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SKRechargeEntities1 : DbContext
    {
        public SKRechargeEntities1()
            : base("name=SKRechargeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminBasic> AdminBasics { get; set; }
        public virtual DbSet<logrfid> logrfids { get; set; }
        public virtual DbSet<BuildingInfo> BuildingInfoes { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<LiuYan> LiuYans { get; set; }
        public virtual DbSet<LogInfo> LogInfoes { get; set; }
        public virtual DbSet<PileInfo> PileInfoes { get; set; }
        public virtual DbSet<RFIDInfo> RFIDInfoes { get; set; }
        public virtual DbSet<UserBalance> UserBalances { get; set; }
        public virtual DbSet<UserBasic> UserBasics { get; set; }
    }
}
